### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by hzdtctc** [JWally/tadpoles-media-downloader#5]
![Capture](https://user-images.githubusercontent.com/111906837/197004585-af404d1c-5829-4697-bf2d-0eaa27b864cc.JPG)

Hi there, seems like a new issue with
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at index.js:264:90
    at Array.filter (<anonymous>)
    at media_getter (index.js:264:50)

Thanks!

**Comment by vanderjs** [comment]
Just commenting to add you aren't alone, I was trying to go through my annual scaping and ran into this same error. Let me know if you were able to find a solution, thanks!

**Comment by hzdtctc** [comment]
> 

Nope. Seems like something changed on the developer side.

**Comment by hzdtctc** [comment]
> Just commenting to add you aren't alone, I was trying to go through my annual scaping and ran into this same error. Let me know if you were able to find a solution, thanks!

Delete length >0 can solve the problem. You can copy my Folk js code and run in Chrome-Console. CDN did not purge code yet.
